<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <?php echo $this->getChildHtml('head');?>
</head>
<?php echo $this->getRequest()->getParams('pid');?>
<body>
    <div class="header"> <?php echo $this->getChildHtml('header');?></div>
    <div class="container">
        <div class="Left">Left</div>
        <div class="Content"><?php echo $this->getChildHtml('content');?></div>
        <div class="Right">Right</div>
    </div>
    <div class="footer"><?php echo $this->getChildHtml('footer');?></div>
</body>
</html>