<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Your Order</title>
</head>
<body>
    <h1 id="h1">Your Order</h1>
<!-- <pre> -->
<div class="container-new">
    <table class="table-new">
        <thead>
            <tr>
                <th>Item Number</th>
                <th>Order Number</th>
                <th>Tax Percent</th>
                <th>Grand Total</th>
                <th>Order Status</th>
                <th>Order Details</th>
                <th>Action</th>
            </tr>
        </thead>
        <?php $a = 1; foreach ($this->getCustomerOrder() as $order) { ?>
            <tbody><form action="<?php echo  Mage::getBaseUrl('customer/order'); ?>" method="post">
            <input type="hidden" name="order_status[from_status]" value="<?php print_r($order->getToStatus()); ?>" >
            <input type="hidden" name="order_status[to_status]" value="cancelled" >
            <input type="hidden" name="order_status[action_by]" value="customer" >
            <input type="hidden" name="order_status[request]" value="1" >
            <input type="hidden" name="order_status[order_id]" value="<?php print_r($order->getOrderId()); ?>" >
            <tr>
                <td><?php echo $a++; ?></td>
                <td><?php print_r($order->getOrderNumber()); ?></td>
                <td><?php print_r($order->getTaxPercent()); ?></td>
                <td><?php print_r($order->getGrandTotal()); ?></td>
                <td><?php print_r($order->getToStatus()); ?></td>
                <td><a class="btn" href="<?php echo Mage::getBaseUrl('customer/order/view'); ?>?id=<?php print_r($order->getOrderId());  ?>"> View
                        </a></td>
                <td><button class="btn">Cancel Order</button></td>
            </tr></form>
            <?php }?>
        </tbody>
    </table>
</div>

</body>
</html>
