<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Your Order</title>
</head>
<body>
    <h1 id="h1">Your Order</h1>
<!-- <pre> -->
<div class="container-new">
    <table class="table-new">
        <thead>
            <tr>
                <th>Item Number</th>
                <th>Order Number</th>
                <th>Product Image</th>
                <th>Product Name</th>
                <th>Product Color</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Row Total</th>
                <th>Tax Percent</th>
                <th>Grand Total</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        <?php $a = 1; foreach ($this->getCustomerOrder() as $order) {
                foreach($this->getOrderItem($order->getOrderId()) as $orderItem) { 
                foreach($this->getProductItem($orderItem->getProductId()) as $productItem){ ?>
            <tr>
                <td><?php echo $a++; ?></td>
                <td><?php print_r($order->getOrderNumber()); ?></td>
                <td><img src="<?php echo Mage::getBaseUrl("media/product/") . $productItem->getImageLink(); ?>" alt="Product Image" class="product-image-new"></td>
                <td><?php print_r($orderItem->getProductName()); ?></td>
                <td><?php print_r($orderItem->getProductColor()); ?></td>
                <td><?php print_r($orderItem->getPrice()); ?></td>
                <td><?php print_r($orderItem->getQty()); ?></td>
                <td><?php print_r($orderItem->getRowTotal()); ?></td>
                <td><?php print_r($order->getTaxPercent()); ?></td>
                <td><?php print_r($order->getGrandTotal()); ?></td>
                <td><button>Cancel Order</button></td>
            </tr>
            <?php }?>
            <?php }?>
            <?php }?>
        </tbody>
    </table>
</div>

</body>
</html>
