      <div class="row border-top border-bottom">
          <?php
          $total=0;
            foreach ($this->getItemList()->getData() as $item) :
                $product = $this->getProductList()->addFieldToFilter('product_id', $item->getProductId())->getData()[0];
            ?>
              <div class="row main align-items-center">
                  <form action="<?php echo Mage::getBaseUrl('sales/quote/add')?>" method="post">
                      <table>
                          <thead>
                              <tr>
                                  <th>Product</th>
                                  <th>Price</th>
                                  <th>Quantity</th>
                                  <th>Total</th>
                                  <th>Action</th>
                              </tr>
                          </thead>
                          <tbody>
                              <tr>
                                  <pre>
                    <td><?php print_r($product->getName()); ?></td>
                    <td><?php print_r($product->getPrice()); ?></td>
                    <input type="hidden" name="cart[product_id]" value="<?php echo $product->getProductId(); ?>">
                    <input type="hidden" name="cart[quote_id]" value="<?php echo $item->getQuoteId(); ?>">
                    <input type="hidden" name="cart[item_id]" value="<?php echo $item->getItemId(); ?>">
                    <td><input type="number" name="cart[qty]" value="<?php print_r($item->getQty()); ?>" min="1"></td>
                    <td><?php print_r($item->getRowTotal()); ?></td>
                    <td>
                        <button class="button" type="submit" name="update">Update</button>
                        <a href="<?php echo Mage::getBaseUrl('sales/quote/delete');?>?quote_id=<?php print_r($item->getQuoteId()); ?>&item_id=<?php print_r($item->getItemId()); ?>" class="button" type="submit" name="remove">Remove</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
              </div>
              <?php $total += $item->getRowTotal();
           endforeach; ?>
          <div class="row main align-items-center button-container">
          <tr>
            <th>Total:   </th><th><?php print_r($total); ?></th>
        <a href="<?php echo Mage::getBaseUrl('catalog/product/view');?>" class="button">Back</a>
          </tr>
    </div>
      </div>