<div class="table">
    <table border="1">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>SKU</th>
            <th>Color</th>
            <th>Size</th>
            <th>Quantity Left</th>
            <th>Description</th>
            <th>ImageLink</th>
            <th>Link</th>
            <th>Category</th>
            <th>Price</th>
            <th>Mfr Cost</th>
            <th>Shipping Cost</th>
            <th>Total Cost</th>
            <th>Margin Percentage</th>
            <th>Min Price</th>
            <th>Status</th>
            <th>UPDATE</th>
            <th>DELETE</th>
        </tr>
        <?php $qty = 0; foreach ($this->getList() as $product) : 
            foreach ($this->getSalesItemData($product->getProductId()) as $item) {
                        $qty = $item->getSumQty();
                    }
                    $Inventory = $product->getInventory();
                    $leftProduct = $Inventory - $qty;
                    $qty = 0;
                    ?>
            <tr>
                <td><?php print_r($product->getProductId()); ?></td>
                <td><?php print_r($product->getName()); ?></td>
                <td><?php print_r($product->getSku()); ?></td>
                <td><?php print_r($product->getColor()); ?></td>
                <td><?php print_r($product->getSize()); ?></td>
                <td><?php echo $product->getInventory(); ?></td>
                <td><?php print_r($product->getDescription()); ?></td>
                <td><?php print_r($product->getImageLink()); ?></td>
                <td>
                     <?php $a = $product->getImageLink(); ?>
                    <img src="<?php echo Mage::getBaseUrl("media/product/") . $a; ?>" class="banner-image">
                </td>
                <td><?php print_r($this->getCategoryNameById(($product->getCategoryId()))); ?></td>
                <td><?php print_r($product->getPrice()); ?></td>
                <td><?php print_r($product->getMfrCost()); ?></td>
                <td><?php print_r($product->getShippingCost()); ?></td>
                <td><?php print_r($product->getTotalCost()); ?></td>
                <td><?php print_r($product->getMarginPercentage()); ?></td>
                <td><?php print_r($product->getMinPrice()); ?></td>
                <td><?php print_r($product->getStatuses()); ?></td>
                <td>
                    <a href="<?php echo$this->getUrl2();?>/form?id=<?php print_r($product->getProductId()); ?>" class="button">Update</a>
        </td>
                <td>
                    <a href="<?php echo$this->getUrl2();?>/delete?id=<?php print_r($product->getProductId()); ?>" class="button">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>