<html>
    <body>
        list phtml content
        <html>
    <body>
        list phtml content
<?php $productModel = $this->getList();
print_r($productModel);die(); ?>
<div class="table" style="margin-top:20px;">
    <table border="1px solid black">
        <tr>
            <th>id</th>
            <th>Name</th>
            <th>SKU</th>
            <th>Type</th>
            <th>Category</th>
            <th>Manufacturer Cost</th>
            <th>Shipping Cost</th>
            <th>Total cost</th>
            <th>Price</th>
            <th>Status</th>
        </tr>

        <tr>
            <td>
                <?php print_r($productModel->getProductId());
                ?>
            </td>
            <td>
                <?php print_r($productModel->getProductName()); ?>
            </td>
            <td>
                <?php print_r($productModel->getSku()); ?>
            </td>
            <td>
                <?php print_r($productModel->getProductType()); ?>
            </td>
            <td>
                <?php print_r($productModel->getCategory()); ?>
            </td>
            <td>
                <?php print_r($productModel->getManufacturerCost()); ?>
            </td>
            <td>
                <?php print_r($productModel->getShippingCost()); ?>
            </td>
            <td>
                <?php print_r($productModel->getTotalCost()); ?>
            </td>
            <td>
                <?php print_r($productModel->getPrice()); ?>
            </td>
            <td>
                <?php print_r($productModel->getStatus()); ?>
            </td>
        </tr>
    </table>
</div>
</body>
</html>
<div class="table" style="margin-top:20px;">
    <table border="1px solid black">
        <tr>
            <th>id</th>
            <th>Name</th>
            <th>SKU</th>
            <th>Type</th>
            <th>Category</th>
            <th>Manufacturer Cost</th>
            <th>Shipping Cost</th>
            <th>Total cost</th>
            <th>Price</th>
            <th>Status</th>
        </tr>

        <tr>
            <td>
                <?php print_r($productModel->getProductId());
                ?>
            </td>
            <td>
                <?php print_r($productModel->getProductName()); ?>
            </td>
            <td>
                <?php print_r($productModel->getSku()); ?>
            </td>
            <td>
                <?php print_r($productModel->getProductType()); ?>
            </td>
            <td>
                <?php print_r($productModel->getCategory()); ?>
            </td>
            <td>
                <?php print_r($productModel->getManufacturerCost()); ?>
            </td>
            <td>
                <?php print_r($productModel->getShippingCost()); ?>
            </td>
            <td>
                <?php print_r($productModel->getTotalCost()); ?>
            </td>
            <td>
                <?php print_r($productModel->getPrice()); ?>
            </td>
            <td>
                <?php print_r($productModel->getStatus()); ?>
            </td>
        </tr>
    </table>
</div>
</body>
</html>