list phtml content
<pre>
<?php
$productCollection = Mage::getModel('catalog/product')->getCollection()
    ->addFieldToFilter('product_name','bet')
    // ->addFieldToFilter('product_name',['like' => 'bet'])
    // ->addFieldToFilter('product_name',['gt' => 'bet'])
    // ->addFieldToFilter('product_name',['in' => 'bet'])
    // ->addFieldToFilter('product_name',['between' => 'bet'])
    ;
foreach($productCollection->getData() as $product) {
    var_dump($product->getStatus());
    print_r($product);
}
// echo get_class($productCollection); 
?>


<?php /*?>
<?php $productModel = Mage::getModel('catalog/product')->load(2); ?>
<div class="table" style="margin-top:20px;">
    <table border="1px solid black">
        <tr>
            <th>id</th>
            <th>Name</th>
            <th>SKU</th>
            <th>Type</th>
            <th>Category</th>
            <th>Manufacturer Cost</th>
            <th>Shipping Cost</th>
            <th>Total cost</th>
            <th>Price</th>
            <th>Status</th>
        </tr>

        <tr>
            <td>
                <?php print_r($productModel->getId());
                ?>
            </td>
            <td>
                <?php print_r($productModel->getProductName()); ?>
            </td>
            <td>
                <?php print_r($productModel->getSku()); ?>
            </td>
            <td>
                <?php print_r($productModel->getProductType()); ?>
            </td>
            <td>
                <?php print_r($productModel->getCategory()); ?>
            </td>
            <td>
                <?php print_r($productModel->getManufacturerCost()); ?>
            </td>
            <td>
                <?php print_r($productModel->getShippingCost()); ?>
            </td>
            <td>
                <?php print_r($productModel->getTotalCost()); ?>
            </td>
            <td>
                <?php print_r($productModel->getPrice()); ?>
            </td>
            <td>
                <?php print_r($productModel->getStatus()); ?>
            </td>
        </tr>
    </table>
</div>
<?php */?>