<div class="table vivek">
    <table border="1">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>STATUS</th>
            <th>UPDATE</th>
            <th>DELETE</th>
        </tr>
    <?php foreach ($this->getList() as $product):?>
        <tr>
            <td>
                <?php print_r($product->getCategoryId());
                ?>
            </td>
            <td>
                <?php print_r($product->getCategoryName()); ?>
            </td>
            <td>
                <?php print_r($product->getStatuses()); ?>
            </td>
            <td>
                <a href="<?php echo$this->getUrl1();?>/form?id=<?php print_r($product->getCategoryId());?>" type="button" id="update" class="button"> Update </a>
            </td>
            <td>
                <a href="<?php echo$this->getUrl1();?>/delete?id=<?php print_r($product->getCategoryId());?>" type="button" id="delete" class="button"> Delete </a>
            </td>
        </tr>
        <?php endforeach;?>
    </table>
</div>