<h1 id="h1">All Order</h1>
<div class="container-new">
    <table class="table-new">
        <thead>
            <tr>
                <th>Item Number</th>
                <th>Customer Id</th>
                <th>Order Number</th>
                <th>Tax Percent</th>
                <th>Grand Total</th>
                <th>Order Details</th>
                <th>Order Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php $a = 1;
            foreach ($this->getCustomerOrder() as $order) { ?>
                <tr>
                    <td><?php echo $a++; ?></td>
                    <td><?php print_r($order->getCustomerId()); ?></td>
                    <td><?php print_r($order->getOrderNumber()); ?></td>
                    <td><?php print_r($order->getTaxPercent()); ?></td>
                    <td><?php print_r($order->getGrandTotal()); ?></td>
                    <td><a class="btn" href="<?php echo Mage::getBaseUrl('admin/order/view'); ?>?id=<?php print_r($order->getOrderId());  ?>"> View
                        </a></td>
                    <td>
                        <form action="<?php echo Mage::getBaseUrl('admin/order'); ?>" method="post">
                        <input type="hidden" name="order_status[order_id]" value="<?php echo $order->getOrderId(); ?>">
                        <input type="hidden" name="order_status[from_status]" value="<?php echo $order->getToStatus(); ?>">
                        <input type="hidden" name="order_status[action_by]" value="Admin">
                            <select name="order_status[to_status]" class="select-box">
                                <?php foreach ($this->getStatusData() as $key => $status) : ?>
                                    <option value="<?php echo $status ?>" <?php echo $status == $order->getToStatus() ? 'selected' : ''; ?>>
                                        <?php echo $status; ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                    </td>
                    <td><button class="btn" type="submit">Submit</button>
                        </form>
                    </td>
                </tr>
            <?php
            } ?>
        </tbody>
    </table>
</div>

</body>

</html>