<h1 id="h1">All Order</h1>
<div class="container-new">
    <table class="table-new">
        <thead>
            <tr>
                <th>Item Number</th>
                <th>Customer Id</th>
                <th>Order Number</th>
                <th>Product Image</th>
                <th>Product Name</th>
                <th>Product Color</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Row Total</th>
                <th>Order Address</th>
            </tr>
        </thead>
        <tbody>
            <?php $a = 1; foreach ($this->getCustomerOrder() as $order) {
                foreach($this->getOrderItem($order->getOrderId()) as $orderItem) { 
                foreach($this->getProductItem($orderItem->getProductId()) as $productItem){ ?>
            <tr>
                <td><?php echo $a++; ?></td>
                <td><?php print_r($order->getCustomerId()); ?></td>
                <td><?php print_r($order->getOrderNumber()); ?></td>
                <td><img src="<?php echo Mage::getBaseUrl("media/product/") . $productItem->getImageLink(); ?>" alt="Product Image" class="product-image-new"></td>
                <td><?php print_r($orderItem->getProductName()); ?></td>
                <td><?php print_r($orderItem->getProductColor()); ?></td>
                <td><?php print_r($orderItem->getPrice()); ?></td>
                <td><?php print_r($orderItem->getQty()); ?></td>
                <td><?php print_r($orderItem->getRowTotal()); ?></td>
                <td><a class="btn" href="<?php echo Mage::getBaseUrl('admin/order/address'); ?>?id=<?php print_r($order->getOrderId());  ?>"> View
                                </a></td>
            </tr>
            <?php } } }?>
            <tr class="cnt"><td>
                <a class="btn" href="<?php echo Mage::getBaseUrl('admin/order/'); ?>"> Back
                </a></td></tr>
        </tbody>
    </table>
</div>

</body>
</html>
