<?php
#// $product_model = $this->getProduct();
?>
<div class="form" style="border:1px solid black; width:30vw; padding: 15px">
    <h2>Product Form</h2>
    <form method="POST" action="<?php echo $this->getUrl('bank/index/save'); ?>">
        <div class="row">
            <input type="hidden" name="bank[id]" value="<?php #echo $product_model->getProductId()?>">
            <input type="hidden" name="bank[session_id]" value="<?php #echo $product_model->getProductId()?>">
        </div>
        <div class="row">
            <label for="sku">User Name  : </label>
            <input type="text" name="bank[user_name]" id="sku" value="<?php #echo $product_model->getSku()?>" >
        </div>
        <div class="row">
            <label for="name">Loan Amount : </label>
            <input type="number" name="bank[loan_amount]" id="name" value="<?php #echo $product_model->getName()?>">
        </div>

        <div class="row">
            <label for="color">Monthly Amount : </label>
            <input type="number" name="bank[monthly_amount]" id="color" value="<?php #echo $product_model->getColor()?>">
        </div>

        <div class="row">
            <label for="category_id">Bank: </label>
            <select name="bank[bank_code]" id="">
                <option value="bank1">bank1</option>
                <option value="bank2">bank2</option>
                <option value="bank3">bank3</option>
                <option value="bank4">bank4</option>
            </select>
        </div>
        <div class="row">
            <label for="category_id">Term: </label>
            <select name="bank[term]" id="">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
            </select>
        </div>
        <div class="row">
            <input type="submit" value="Submit">
        </div>
    </form>
</div>