<html>
    <body>
        <h1>
            CONTENT
        </h1>
        <pre>
        <?php
    //    echo  $this->getRequest()->getparams("id");
       $productModel = Mage::getModel("Catalog/Product")->load(16);
       echo "<pre>";
    //    print_r($productModel->load(12));
       print_r($productModel->getId()); 
       print_r($productModel->getProduct_name());
       print_r($productModel->getsku());
    //    print_r($productModel);
        ?>
    </body>
</html>