 <?php
    $this->getChildHtml('');
    //    echo  $this->getRequest()->getparams("id");
    //    $productModel = Mage::getModel("Admin_Controller_Catalog/Product")->load(16);
    //    print_r($productModel->load(12));
    //    print_r($productModel->getId()); 
    //    print_r($productModel->getProduct_name());
    //    print_r($productModel->getsku());
    //    print_r($productModel);
    ?>