<div class="header">
<a href="#"><img id="logo" src=<?php echo Mage::getBaseUrl()."\skin\image\ccc.jpg" ?> alt="Your Logo"></a>
  <div class="header-right">
    <div class="pill-nav" id="myDIV">
      <ul>
        <a class="btn active"href="<?php echo$this->getHeaderUrl("admin/catalog_product/form");?>">Product Form</a>
        <a class="btn"  href=" <?php echo$this->getHeaderUrl("admin/catalog_product/list");?>">Product List</a>
        <a class="btn" href="<?php echo$this->getHeaderUrl("admin/catalog_category/form");?>">Category Form</a>
        <a class="btn" href="<?php echo$this->getHeaderUrl("admin/catalog_category/list");?>">Category List</a>
        <a class="btn" href="<?php echo$this->getHeaderUrl("customer/account/login");?>">Login</a>
      </ul>
    </div>
  </div>
</div>
