<?php $URL = Mage::getBaseUrl(); ?>
<div class="header">
<a href="#"><img id="logo" src=<?php echo Mage::getBaseUrl()."\skin\image\ccc.jpg" ?> alt="Your Logo"></a>
  <div class="header-right">
    <div class="pill-nav">
      <ul>
        <a class="active" href="<?php echo $URL; ?>/admin/catalog_product/form">Product Form</a>
        <a href="<?php echo $URL; ?>/admin/catalog_product/list">Product List</a>
        <a href="<?php echo $URL; ?>/admin/catalog_category/form">Category Form</a>
        <a href="<?php echo $URL; ?>/admin/catalog_category/list">Category List</a>
      </ul>
    </div>
  </div>
</div>