<div class="header">
<a href="#"><img id="logo" src=<?php echo Mage::getBaseUrl()."\skin\image\ccc.jpg" ?> alt="Your Logo"></a>
  <div class="header-right">
    <div class="pill-nav" id="myDIV">
      <ul>
        <a class="btn"href="<?php echo$this->getHeaderUrl("");?>">Home</a>
        <a class="btn"href="<?php echo$this->getHeaderUrl("catalog/product/view");?>">Product</a>
        <a class="btn" href="<?php echo$this->getHeaderUrl("customer/account/login");?>">Login</a>
        <a class="btn" href="<?php echo$this->getHeaderUrl("customer/account/logout");?>">Log Out</a>
      </ul>
    </div>
  </div>
</div>
