
<table border="1px">
    <tr>
        <th>Product Id</th>
        <th>Image</th>
        <th>Name</th>
        <th>Color</th>
        <th>Description</th>
        <th colspan=2>AddTocart</th>
    </tr>
    <?php foreach ($this->getItem() as $product) { ?>
        <td>
            <?php echo $product->getProductId(); ?>
        </td>
        <td>
            <img src="<?php echo Mage::getBaseUrl('media/product/'). $product->getImageLink(); ?>" style="width:200px" alt=""> 
        </td>
        <td>
            <?php echo $product->getName(); ?>
        </td>
        <td>
            <?php echo $product->getColor(); ?>
        </td>
        <td>
            <?php echo $product->getDescription(); ?>
        </td>


        <form method="POST" action="<?php echo $this->getUrl('sales/quote/add') ?>">
            <td>
                <div class="form">
                    <?php //$categoryModel = $this->getCategoryForm();                         ?>
                    <div class="row">
                        <input type="hidden" name="sales[product_id]" value="<?php echo $product->getProductId(); ?>">
                    </div>
                    <div class="row">
                        <label for="quentity">Quentity : </label>
                        <input type="text" name="sales[quentity]" id="quentity"
                            value="<?php //echo $product->getQuentity();                         ?>">
                    </div>
                </div>
            </td>
            <td>
                <div class="row">
                    <input type="submit" value="AddToCart">
                </div>
            </td>
        </form>

    <?php } ?>
</table>