<div class="table">
    <table border="1">
        <tr>
            <th>Customer Email</th>
            <th>Name</th>
            <th>Billing Address</th>
            <th>Billing City</th>
            <th>Billing Region</th>
            <th>Billing Country</th>
            <th>Billing Phone</th>
            <th>Shipping Address</th>
            <th>Shipping City</th>
            <th>Shipping Region</th>
            <th>Shipping Country</th>
            <th>Shipping Phone</th>
            <th>Default</th>
        </tr>
        <?php foreach ($this->getCustomer() as $product) : ?>
            <tr>
                <td><?php print_r($product->getCustomerEmail()); ?></td>
                <td><?php print_r($product->getFirstName().$product->getLastName()); ?></td>
                <td><?php print_r($product->getBillingAddress()); ?></td>
                <td><?php print_r($product->getBillingCity()); ?></td>
                <td><?php print_r($product->getBillingRegion()); ?></td>
                <td><?php print_r($product->getBillingCountry()); ?></td>
                <td><?php print_r($product->getBillingPhone()); ?></td>
                <td><?php print_r($product->getShippingAddress()); ?></td>
                <td><?php print_r($product->getShippingCity()); ?></td>
                <td><?php print_r($product->getShippingRegion()); ?></td>
                <td><?php print_r($product->getShippingCountry()); ?></td>
                <td><?php print_r($product->getShippingPhone()); ?></td>
                <td><?php print_r($product->getDefault()); ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>