<?php 
// echo $this->getField();
// die;
?>

<div class="form">
    <h2>Customer Login</h2>
    <form method="POST" action="<?php echo $this->getUrl('customer/account/login') ?>">
        <div class="row">
            <div>
                <label for="customer_email">Email:</label>
                <input type="text" value="" name="customer[customer_email]" id="customer_email">
            </div>
            <div>
                <label for="password">Password:</label>
                <input type="password" value="" name="customer[password]" id="password">
            </div>
        </div>
        <div>
            <input type="submit" name="submit" value="Submit">
            <a href="<?php echo $this->getUrl('customer/account/register') ?>" class="register-link">Register</a>
        </div>
    </form>
</div>