<div class="tab-pane fade" id="password" role="tabpanel" aria-labelledby="password-tab">
						<form action="<?php echo $this->getUrl('customer/account/password') ?>" method="post" onsubmit="return myfun()" >
						<h3 class="mb-4">Password Settings</h3>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<?php $customerId = Mage::getSingleton('core/session')->get('logged_in_customer_user_id'); ?>
								<input type="hidden" class="form-control" id="customer_id" name="password[customer_id]" value="<?php echo $customerId ; ?>">
								  	<label>Old password</label>
								  	<input type="password" class="form-control" id="pass" name="password[old_password]" value="">
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
								  	<label>New password</label>
								  	<input type="password" class="form-control" id="npass" name="password[password]" value="">
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
								  	<label>Confirm new password</label>
								  	<input type="password" class="form-control" id="cpass" name="cpass" value="">
								</div>
								

							</div>
							<div>
							<span id="mess" style="text-align: center; color:red"></span>
							</div>
						</div>
						<div>
							<button class="btn btn-primary">Update</button>
							<button class="btn btn-light">Cancel</button>
						</div>
						</form>
					</div>